name: Testes de API Automatizados usando Postman CLI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instalação do Postman CLI no Ubuntu
      - name: Instalar Postman CLI
        run: |
          wget https://dl-cli.pstmn.io/install/linux64.sh
          chmod +x linux64.sh
          sudo ./linux64.sh

      # Login no Postman CLI usando a chave da API armazenada nos segredos do GitHub
      - name: Login no Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Executa a collection do Postman
      - name: Executar testes de API
        run: |
          postman collection run "nagem_tst_pix.postman_collection.json"
